#!/bin/bash

export PYTHONPATH=/home/expdev/SRW/env/work/srw_python:$PYTHONPATH
export SIREPO_AUTH_METHODS=guest
export SIREPO_CELERY_TASKS_CELERYD_TASK_TIME_LIMIT=259200  # 3 days = 3 * 24 * 3600
export SIREPO_CELERY_TASKS_CELERYD_CONCURRENCY=20
export SIREPO_FEATURE_CONFIG_SIM_TYPES=srw
export SIREPO_MPI_CORES=21
export SIREPO_SERVER_DB_DIR=/home/expdev/sirepo/run
export SIREPO_SERVER_JOB_QUEUE=Celery
